hub_registry:
  container_name: hub_registry
  restart: always
  image: registry:2
  ports:
    - "5000:5000"
  environment:
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    # LOAD BALANCER
    VIRTUAL_HOST: "https://api-hub.private.dev, api-hub.private.dev"
    FORCE_SSL: "yes"
    #REGISTRY_STORAGE_DELETE_ENABLED: "True"
  volumes:
    - ./data:/var/lib/registry    
    - ./auth:/auth


hub_front:
  container_name: hub_front
  image: konradkleine/docker-registry-frontend:v2
  links:
    - hub_registry
  environment:
    ENV_DOCKER_REGISTRY_HOST: 'hub_registry'
    ENV_DOCKER_REGISTRY_PORT: 5000
    # ENV_REGISTRY_PROXY_FQDN: 'hub.rcp.pe'
    # ENV_REGISTRY_PROXY_PORT: 80
    ENV_REGISTRY_PROXY_FQDN: 'hub.devteam.dev'
    ENV_REGISTRY_PROXY_PORT: 80
    # LOAD BALANCER
    VIRTUAL_HOST: "https://hub.private.dev, hub.private.dev"
    FORCE_SSL: "yes"
  ports:
    - "80:80"
